import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import {
  Heading,
  Box,
  Center,
  Flex,
 Select,
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  Text,
} from "@chakra-ui/react";
import { uselogic } from '@/hooks/useLogic';
import { useState } from 'react'
import { ethers } from 'ethers'


const inter = Inter({ subsets: ['latin'] })

const TransactionTable = (props) => {
  return (
    <TableContainer>
      <Table variant="simple">
        <TableCaption>Imperial to metric conversion factors</TableCaption>
        <Thead>
          <Tr>
            <Th>sender address</Th>
            <Th>receiver address</Th>
            <Th isNumeric>amount sent</Th>
          </Tr>
        </Thead>
        <Tbody>
          {props.selectedtoken.length === 0 ? (
            <Tr justifyContent="center">
              <Text pt="50px">select token to track</Text>
            </Tr>
          ) : (
            <>
              {props.selectedtoken.map((eachtransaction) =>{
                console.log('hello',eachtransaction)
                return (
                <>
                  <Tr>
                    <Td>{eachtransaction.from}</Td>
                    <Td>{eachtransaction.to}</Td>
                    <Td isNumeric>{ ethers.utils.formatEther(eachtransaction.value) }</Td>
                  </Tr>
                </>
              )

              } )}
            </>
          )}
        </Tbody>
      </Table>
    </TableContainer>
  );
};

export default function Home() {
  const {
    transactionObjectsUSDT,
    transactionObjectsUSDC,
    transactionObjectsDAI,
  } = uselogic();

  const transactionobject = {
    USDT: transactionObjectsUSDT,
    DAI: transactionObjectsDAI,
    USDC: transactionObjectsUSDC,
  };
  const [tokenToTrack, setTokenToTrack] = useState([]);
  console.log(
    "helper",
    transactionObjectsUSDT,
    transactionObjectsDAI,
    transactionObjectsUSDC
  );

  const onChangeHandler = (e) => {
    setTokenToTrack(transactionobject[e.target.value]);
    console.log('tester',transactionobject[e.target.value])
  };
  return (
    <>
      <Head>
        <title>ERC20 TOKEN TRANSFER TRACKER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
         <Heading>Welcome to ERC20 TOKEN Transfer Tracker</Heading>
        <Center>
          <Box
            bg="white"
            w="70vw"
            minH="70vh"
            mt="1rem"
            borderRadius="10px"
            p="2rem"
          >
            <Flex justifyContent="space-between">
              <Box>
                <Flex alignItems="center">
                  Supportedtoken:&nbsp;&nbsp;
                  <Select
                    w="auto"
                    onChange={onChangeHandler}
                    placeholder="Select option"
                    borderRadius="1rem"
                  >
                    <option value="USDT">USDT</option>
                    <option value="DAI">DAI</option>
                    <option value="USDC">USDC</option>
                  </Select>
                </Flex>
              </Box>
              {/* <Box>
            <AddTicketModal/>
          </Box> */}
            </Flex>
            <br></br>
            <TransactionTable selectedtoken={tokenToTrack}></TransactionTable>
          </Box>
        </Center>
      </main>
    </>
  )
}
